import { Metadata } from "next";

export const metadata: Metadata = {
  title: "this is the page",
  description: "Generated by create next app",
};

export default function PagesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <header>page header</header>
      {children}
      <footer>page footer</footer>
    </div>
  );
}
